// Textes de la page, en français et en anglais.
//
// La langue vient du navigateur, et un sélecteur la remplace. Le choix tient
// dans l'adresse, comme les filtres : une page rechargée reste dans la même
// langue, et un lien la conserve.
const STRINGS = {
  fr: {
    lang: 'fr',
    storageTitle: 'Stockage des archives',
    storageHelp: 'Vos archives sont enregistrées sur cet ordinateur.',
    storageOpen: 'Ouvrir le dossier',
    storageEdit: 'Modifier…',
    storageDestination: 'Nouveau dossier des archives',
    storageDestinationHint: 'Choisissez ou saisissez un dossier',
    storageReview: 'L’application copie vos archives, vérifie la copie, puis utilise ce nouveau dossier. Le dossier précédent est conservé ; les nouvelles archives seront enregistrées dans le nouveau.',
    storageConfirm: 'Copier et utiliser ce dossier',
    storageCancel: 'Annuler',
    storageProgress: 'Progression de la copie des archives',
    storagePending: 'Préparation de la copie…',
    storageCopying: 'Copie des archives…',
    storageVerifying: 'Vérification de la copie…',
    storageSwitching: 'Activation du nouveau dossier…',
    storageCount: (done,total) => `${done} / ${total} fichiers`,
    storageDone: 'Le nouveau dossier est actif. Votre ancien dossier a été conservé.',
    storageError: 'Le changement de dossier n’a pas abouti.',
    storageUnavailable: 'Le stockage est momentanément inaccessible. Nouvelle vérification automatique…',
    storageOpenError: 'Impossible d’ouvrir le dossier. Vous pouvez copier le chemin affiché ci-dessus.',
    storagePickDone: 'Dossier choisi. Vérifiez votre choix avant de lancer la copie.',
    storagePickFailed: 'Sélecteur indisponible. Vous pouvez saisir le chemin du dossier.',
    technicalTitle: 'Dossiers et extension',
    exportLocation: 'Voir le chemin du dernier export',
    exportPartial: 'Export incomplet',
    exportReady: 'Export terminé',
    exportOptions: 'Options et contenu de l’export',
    exportFolderLabel: 'Enregistrer dans',
    exportHelp: 'Deux CSV, les médias et les métadonnées complètes, dans un dossier daté.',
    addNoteLabel: 'Note facultative',
    addHelp: 'Collez les liens des posts à conserver, une adresse par ligne.',
    backToArchives: '↑ Vos archives',
    actionsAria: 'Actions de la bibliothèque',
    title: 'Archivage X',
    tagline: 'Vos posts, médias et compteurs, conservés sur votre disque.',

    setupChecking: 'Vérification…',
    setupCheckingSlow: 'La vérification de l’extension prend plus de temps que prévu.',
    setupPairFailed: 'La connexion à l’extension a échoué. Réessayez.',
    setupLoadExtension: 'Chargez l’extension dans votre navigateur, puis connectez-la.',
    setupNoSession: 'Connectez-vous à X dans ce navigateur, puis cliquez sur le bouton ci-contre.',
    setupPaired: 'Extension connectée',
    setupSessionLive: 'connexion X active',
    setupSessionStored: 'connexion X en place',
    pairButton: 'Connecter l’extension',
    sessionButton: 'Utiliser ma connexion X',

    addTitle: 'Ajouter des posts',
    addPlaceholder: 'https://x.com/nom/status/123\nhttps://x.com/nom/status/456',
    addAria: 'Adresses des posts',
    addOptions: 'Options d’archivage',
    addNote: 'Note : streamer, passage, raison du choix',
    addReplies: 'Archiver aussi les réponses',
    addRefresh: 'Actualiser les compteurs des posts déjà archivés',
    addSubmit: 'Ajouter',
    addResult: (ok, bad) => `${ok} ajoutée${ok > 1 ? 's' : ''}${bad ? `, ${bad} refusée${bad > 1 ? 's' : ''}` : ''}.`,

    exportTitle: 'Exporter en CSV',
    exportFolder: 'Dossier où écrire l’export',
    exportChoose: 'Parcourir…',
    exportSubmit: 'Exporter',
    exportOld: 'Ajouter les posts de la collecte automatique',
    exportWhat: 'Ce que contient un export',
    exportWhatBody: 'Deux tableaux : un par post, un par relevé de compteurs. Les médias et les données complètes de chaque post les accompagnent. Chaque export crée un dossier daté et ne redemande rien à X.',
    exportRunning: 'Export en cours…',
    exportDone: (n, files) => `${n} posts · ${files} fichiers copiés`,
    exportMissing: n => `${n} fichier${n > 1 ? 's' : ''} manquant${n > 1 ? 's' : ''}. Consultez le rapport dans l’export.`,
    exportGone: 'Le dernier dossier d’export est introuvable. Vous pouvez créer un nouvel export.',
    exportPickHint: 'La fenêtre de choix peut se cacher derrière le navigateur.',
    exportPickCancelled: 'Sélection annulée.',
    exportPickDone: 'Dossier choisi. Cliquez sur Exporter.',
    exportPickFailed: 'Sélecteur indisponible. Saisissez le chemin à la main.',
    exportRefused: 'Export non lancé. Vérifiez le chemin, ou attendez la fin du précédent.',
    exportUnreachable: 'Export injoignable. Rechargez la page.',

    filterTitle: 'Filtrer les archives',
    filterSearch: 'Chercher dans le texte ou le compte',
    filterCategory: 'Toutes les catégories',
    filterCategoryAria: 'Catégorie',
    catTip: 'Ranger ce post dans une autre catégorie',
    catNew: 'Nouvelle catégorie…',
    catPrompt: 'Nom de la nouvelle catégorie',
    catFailed: 'Rangement impossible',
    exportScope: 'Contenu',
    exportScopeAll: 'Toutes les catégories',
    filterAccount: 'Compte',
    filterFrom: 'Publié du',
    filterTo: 'au',
    filterFromAria: 'Publié à partir du',
    filterToAria: 'Publié jusqu’au',
    filterReset: 'Réinitialiser',
    filterMedia: 'Média',
    filterState: 'État',
    filterAll: 'Tous',
    filterVideo: 'Vidéo',
    filterPhoto: 'Photo',
    filterFailed: 'En échec',
    filterRunning: 'En cours',
    sortAria: 'Trier',
    sortRecent: 'Archivés en dernier',
    sortOldest: 'Archivés en premier',
    sortPublished: 'Publiés en dernier',
    sortPublishedAsc: 'Publiés en premier',
    sortViews: 'Plus vus',
    sortLikes: 'Plus aimés',
    sortReposts: 'Plus repartagés',

    listTitle: 'Vos archives',
    retryAll: 'Tout réessayer',
    retryAllCount: n => `Tout réessayer (${n})`,
    retryAllTip: n => `Remettre en file ${n} post${n > 1 ? 's' : ''} en échec`,
    retryAllNone: 'Aucun post en échec',
    retryProgress: (i, n) => `Remise en file ${i}/${n}…`,
    retryDone: (ok, bad) => `${ok} post${ok > 1 ? 's' : ''} remis en file${bad ? ` · ${bad} refusé${bad > 1 ? 's' : ''}` : ''}.`,
    retryUnreachable: 'Le service ne répond pas, aucun post n’a été relancé.',

    range: (a, b, total) => `${a} à ${b} sur ${total}`,
    noResult: 'aucun résultat',
    resultCount: n => `${n} résultats`,
    empty: 'Aucune archive ne correspond.',
    unreachable: 'Le service ne répond pas.',
    quotaWait: at => `X limite le rythme. Reprise vers ${at}, sans rien perdre.`,
    sessionStale: 'Votre connexion à X a expiré. Reconnectez-vous. Les archives restent intactes.',

    published: at => `publié le ${at}`,
    archivedAt: at => `archivé le ${at}`,
    views: n => `${n} vues`,
    likes: n => `${n} j’aime`,
    reposts: n => `${n} reposts`,
    noCounts: 'Pas encore de compteurs.',
    playAria: who => `Lire la vidéo de ${who}`,
    videoAria: who => `Vidéo de ${who}`,
    thisPost: 'ce post',

    wipeTip: 'Supprimer cette archive : texte, compteurs, médias et données du post',
    wipeConfirm: 'Supprimer ?',
    wipeConfirmTip: 'Cliquez à nouveau pour supprimer. Rien ne pourra être récupéré.',
    wipeRunning: 'Suppression…',
    wipeShared: 'Média lié',
    wipeFailed: 'Échec',
    wipeLeft: 'Des fichiers subsistent',
    sharedNote: n => n > 1
      ? `Un média de ce post est aussi utilisé par ${n} autres archives. Il sera conservé pour elles.`
      : 'Un média de ce post est aussi utilisé par une autre archive. Il sera conservé pour elle.',
    linkedPosts: 'Post lié',
    linkedRelation: relation => ({quote: 'Post cité', repost: 'Post reposté',
      raw_response: 'Réponse brute partagée'}[relation] || 'Média partagé'),
    wipeKeepShared: 'Supprimer ce post, garder le média',

    pairing: 'Connexion…',
    pairMissing: 'L’extension n’a pas répondu. Vérifiez son installation et son activation dans ce navigateur, puis rechargez cette page. Le guide d’installation précise les étapes pour chaque navigateur.',
    filesAre: 'Archive de travail',
    postsAre: 'Données des posts',
    extensionIs: 'Dossier de l’extension Chrome',
    langAria: 'Langue',
  },

  en: {
    lang: 'en',
    storageTitle: 'Archive storage',
    storageHelp: 'Your archives are saved on this computer.',
    storageOpen: 'Open folder',
    storageEdit: 'Change…',
    storageDestination: 'New archive folder',
    storageDestinationHint: 'Choose or enter a folder',
    storageReview: 'The app copies your archives, checks the copy, then uses this new folder. The previous folder is kept; new archives will be saved in the new folder.',
    storageConfirm: 'Copy and use this folder',
    storageCancel: 'Cancel',
    storageProgress: 'Archive copy progress',
    storagePending: 'Preparing to copy…',
    storageCopying: 'Copying archives…',
    storageVerifying: 'Checking the copy…',
    storageSwitching: 'Activating the new folder…',
    storageCount: (done,total) => `${done} / ${total} files`,
    storageDone: 'The new folder is active. Your previous folder has been kept.',
    storageError: 'The folder change could not be completed.',
    storageUnavailable: 'Storage is temporarily unavailable. Checking again automatically…',
    storageOpenError: 'Unable to open the folder. You can copy the path shown above.',
    storagePickDone: 'Folder selected. Review your choice before starting the copy.',
    storagePickFailed: 'Folder picker unavailable. You can enter the folder path.',
    technicalTitle: 'Folders and extension',
    exportLocation: 'View the last export’s folder path',
    exportPartial: 'Export incomplete',
    exportReady: 'Export complete',
    exportOptions: 'Export options and contents',
    exportFolderLabel: 'Save to',
    exportHelp: 'Two CSVs, media and full metadata, in a dated folder.',
    addNoteLabel: 'Optional note',
    addHelp: 'Paste the links of posts to keep, one address per line.',
    backToArchives: '↑ Your archive',
    actionsAria: 'Library actions',
    title: 'X Archive',
    tagline: 'Your posts, media and counts, saved on your own disk.',

    setupChecking: 'Checking…',
    setupCheckingSlow: 'Checking the extension is taking longer than expected.',
    setupPairFailed: 'The extension connection failed. Please try again.',
    setupLoadExtension: 'Load the extension in your browser, then connect it.',
    setupNoSession: 'Sign in to X in this browser, then click the button next to this text.',
    setupPaired: 'Extension connected',
    setupSessionLive: 'X connection active',
    setupSessionStored: 'X connection stored',
    pairButton: 'Connect the extension',
    sessionButton: 'Use my X connection',

    addTitle: 'Add posts',
    addPlaceholder: 'https://x.com/name/status/123\nhttps://x.com/name/status/456',
    addAria: 'Post addresses',
    addOptions: 'Archiving options',
    addNote: 'Note: streamer, moment, why you kept it',
    addReplies: 'Archive the replies as well',
    addRefresh: 'Refresh counts for posts already archived',
    addSubmit: 'Add',
    addResult: (ok, bad) => `${ok} added${bad ? `, ${bad} refused` : ''}.`,

    exportTitle: 'Export to CSV',
    exportFolder: 'Folder to write the export into',
    exportChoose: 'Browse…',
    exportSubmit: 'Export',
    exportOld: 'Add posts from the automatic collection',
    exportWhat: 'What an export contains',
    exportWhatBody: 'Two tables: one per post, one per reading of the counts. The media and the full data of each post come with them. Each export creates a dated folder and asks X for nothing.',
    exportRunning: 'Export running…',
    exportDone: (n, files) => `${n} posts · ${files} files copied`,
    exportMissing: n => `${n} file${n === 1 ? '' : 's'} missing. See the report in the export folder.`,
    exportGone: 'The last export folder could not be found. You can create a new export.',
    exportPickHint: 'The folder window may hide behind the browser.',
    exportPickCancelled: 'Cancelled.',
    exportPickDone: 'Folder chosen. Click Export.',
    exportPickFailed: 'Folder picker unavailable. Type the path instead.',
    exportRefused: 'Export not started. Check the path, or wait for the previous one.',
    exportUnreachable: 'Export unreachable. Reload the page.',

    filterTitle: 'Filter the archive',
    filterSearch: 'Search the text or the account',
    filterCategory: 'All categories',
    filterCategoryAria: 'Category',
    catTip: 'Move this post to another category',
    catNew: 'New category…',
    catPrompt: 'Name of the new category',
    catFailed: 'Could not move it',
    exportScope: 'Include',
    exportScopeAll: 'All categories',
    filterAccount: 'Account',
    filterFrom: 'Posted from',
    filterTo: 'to',
    filterFromAria: 'Posted on or after',
    filterToAria: 'Posted on or before',
    filterReset: 'Reset',
    filterMedia: 'Media',
    filterState: 'State',
    filterAll: 'All',
    filterVideo: 'Video',
    filterPhoto: 'Photo',
    filterFailed: 'Failed',
    filterRunning: 'Running',
    sortAria: 'Sort',
    sortRecent: 'Archived last',
    sortOldest: 'Archived first',
    sortPublished: 'Posted last',
    sortPublishedAsc: 'Posted first',
    sortViews: 'Most viewed',
    sortLikes: 'Most liked',
    sortReposts: 'Most reposted',

    listTitle: 'Your archive',
    retryAll: 'Retry all',
    retryAllCount: n => `Retry all (${n})`,
    retryAllTip: n => `Queue ${n} failed post${n > 1 ? 's' : ''} again`,
    retryAllNone: 'No failed post',
    retryProgress: (i, n) => `Queueing ${i}/${n}…`,
    retryDone: (ok, bad) => `${ok} post${ok > 1 ? 's' : ''} queued again${bad ? ` · ${bad} refused` : ''}.`,
    retryUnreachable: 'The service does not answer, no post was queued.',

    range: (a, b, total) => `${a} to ${b} of ${total}`,
    noResult: 'no result',
    resultCount: n => `${n} results`,
    empty: 'No archive matches.',
    unreachable: 'The service does not answer.',
    quotaWait: at => `X is throttling. Back around ${at}, nothing is lost.`,
    sessionStale: 'Your connection to X has expired. Sign in again. The archive stays intact.',

    published: at => `posted ${at}`,
    archivedAt: at => `archived ${at}`,
    views: n => `${n} views`,
    likes: n => `${n} likes`,
    reposts: n => `${n} reposts`,
    noCounts: 'No counts yet.',
    playAria: who => `Play the video from ${who}`,
    videoAria: who => `Video from ${who}`,
    thisPost: 'this post',

    wipeTip: 'Delete this archive: text, counts, media and post data',
    wipeConfirm: 'Delete?',
    wipeConfirmTip: 'Click again to delete. Nothing can be recovered.',
    wipeRunning: 'Deleting…',
    wipeShared: 'Linked media',
    wipeFailed: 'Failed',
    wipeLeft: 'Some files remain',
    sharedNote: n => n > 1
      ? `A media file from this post is also used by ${n} other archives. It will be kept for them.`
      : 'A media file from this post is also used by another archive. It will be kept for it.',
    linkedPosts: 'Linked post',
    linkedRelation: relation => ({quote: 'Quoted post', repost: 'Reposted post',
      raw_response: 'Shared raw response'}[relation] || 'Shared media'),
    wipeKeepShared: 'Delete this post, keep the media',

    pairing: 'Connecting…',
    pairMissing: 'The extension did not respond. Check that it is installed and enabled in this browser, then reload this page. The installation guide has instructions for each browser.',
    filesAre: 'Working archive',
    postsAre: 'Post data',
    extensionIs: 'Chrome extension folder',
    langAria: 'Language',
  },
};

function pickLanguage() {
  const asked = new URLSearchParams(location.search).get('lang');
  if (STRINGS[asked]) return asked;
  return (navigator.language || 'fr').toLowerCase().startsWith('en') ? 'en' : 'fr';
}

let LANG = pickLanguage();
const T = key => STRINGS[LANG][key];

function applyStatic() {
  document.documentElement.lang = LANG;
  for (const node of document.querySelectorAll('[data-t]')) node.textContent = T(node.dataset.t);
  for (const node of document.querySelectorAll('[data-t-placeholder]')) node.placeholder = T(node.dataset.tPlaceholder);
  for (const node of document.querySelectorAll('[data-t-aria]')) node.setAttribute('aria-label', T(node.dataset.tAria));
  document.title = T('title');
}
